### ISSUE TITLE
Doesn't work( goes on a loop)

### ISSUE THREAD

**Issue by Sirius-Black4** [khansaad1275/Termux-Games#1]
I ran installation and games but i can never play. Done all steps properly. After selecting game goes on loop back to home screen.

**Comment by khansaad1275** [comment]
> I ran installation and games but i can never play. Done all steps properly. After selecting game goes on loop back to home screen.

Bro are you using this in termux?

**Comment by khansaad1275** [comment]
> I ran installation and games but i can never play. Done all steps properly. After selecting game goes on loop back to home screen.

I have solved the issue, please check and reply 😊

**Comment by Sirius-Black4** [comment]
> > I ran installation and games but i can never play. Done all steps properly. After selecting game goes on loop back to home screen.
> 
> I have solved the issue, please check and reply

Sure will do that.

**Comment by Sirius-Black4** [comment]
Can this work without Termux?

**Comment by khansaad1275** [comment]
> Can this work without Termux?

It can but I have to make a new script for that
