### ISSUE TITLE
It keep goes on loop on chosing nInvaders option

### ISSUE THREAD

**Issue by kmaaz-dev** [khansaad1275/Termux-Games#2]
When I chose the option 4 i.e ninvaders game , it restarts  everytime . 
One seeing a script , looks like there is cap mistake on **line 74 of games.sh**
On doing 1 change i.e changing the command from **nInvaders** to **ninvaders**  , it works 

Please check the script

**Comment by khansaad1275** [comment]
> When I chose the option 4 i.e ninvaders game , it restarts everytime .
> One seeing a script , looks like there is cap mistake on **line 74 of games.sh**
> On doing 1 change i.e changing the command from **nInvaders** to **ninvaders** , it works
> 
> Please check the script

Solved it
