### ISSUE TITLE
Why does your install.sh script overwrite the user's bashrc file? This is a terrible security flaw. 

### ISSUE THREAD

**Issue by commercialdrive** [khansaad1275/Termux-Games#7]
Why does your install.sh script overwrite the user's bashrc file? This is a terrible security flaw.  You even change the user's prompt. Howcome?

-CD

**Comment by khansaad1275** [comment]
> Why does your install.sh script overwrite the user's bashrc file? This is a terrible security flaw. You even change the user's prompt. Howcome?
> 
> -CD

😅 Maybe that time i didn't knew i can append the alias too. I am gonna update it. Thanks

**Comment by khansaad1275** [comment]
> Why does your install.sh script overwrite the user's bashrc file? This is a terrible security flaw. You even change the user's prompt. Howcome?
> 
> -CD

Updated the script, thanks.
